### ISSUE TITLE
connection-profile.yaml file for the SDK

### ISSUE THREAD

**Issue by mvanmeerbeck** [bxforce/bnc-hlf#16]
The java fabric SDK needs the connection-profile.yaml file to connect to the peer:
https://hyperledger.github.io/fabric-gateway-java/master/org/hyperledger/fabric/gateway/Gateway.Builder.html#networkConfig-java.nio.file.Path-

There are multiple connection-profile file in `hyperledger-fabric-network/settings` but they don't seem to be complete. Which one is the right one ?

Currently, my connection-profile (not in bnc) looks like this
```
---
name: ipng.libriciel.fr
version: 1.0.0
client:
    organization: Org1
    connection:
        timeout:
            peer:
                endorser: '300'
organizations:
    Org1:
        mspid: Org1MSP
        peers:
            - peer0.org1.ipng.libriciel.fr
            - peer1.org1.ipng.libriciel.fr
        certificateAuthorities:
            - ca.org1.ipng.libriciel.fr
    Org2:
        mspid: Org2MSP
        peers:
            - peer0.org2.ipng.libriciel.fr
            - peer1.org2.ipng.libriciel.fr
        certificateAuthorities:
            - ca.org2.ipng.libriciel.fr
channels:
    ipng-channel:
        orderers:
            - orderer.ipng.libriciel.fr
        peers:
            peer0.org1.ipng.libriciel.fr:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
            peer1.org1.ipng.libriciel.fr:
                endorsingPeer: false
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
            peer0.org2.ipng.libriciel.fr:
                endorsingPeer: true
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
            peer1.org2.ipng.libriciel.fr:
                endorsingPeer: false
                chaincodeQuery: true
                ledgerQuery: true
                eventSource: true
orderers:
    orderer.ipng.libriciel.fr:
        url: grpcs://orderer.ipng.libriciel.fr:7050
        tlsCACerts:
            pem: |
                -----BEGIN CERTIFICATE-----
                MIICWzCCAgGgAwIBAgIQZ9g2P8D6pFq/HFSyF2h0XjAKBggqhkjOPQQDAjB4MQsw
                CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
                YW5jaXNjbzEaMBgGA1UEChMRaXBuZy5saWJyaWNpZWwuZnIxIDAeBgNVBAMTF3Rs
                c2NhLmlwbmcubGlicmljaWVsLmZyMB4XDTE5MTIwNDEwNTMwMFoXDTI5MTIwMTEw
                NTMwMFoweDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNV
                BAcTDVNhbiBGcmFuY2lzY28xGjAYBgNVBAoTEWlwbmcubGlicmljaWVsLmZyMSAw
                HgYDVQQDExd0bHNjYS5pcG5nLmxpYnJpY2llbC5mcjBZMBMGByqGSM49AgEGCCqG
                SM49AwEHA0IABPQHbpNJruzqn43LLpEuiEYsmjCckoA5qDYvQOSl4IBFNGSXzGCU
                esAn+b/OaL8NAlIcA9ebf4EZwxoRoSb0zl2jbTBrMA4GA1UdDwEB/wQEAwIBpjAd
                BgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYDVR0TAQH/BAUwAwEB/zAp
                BgNVHQ4EIgQg3+8/kszFgUIWLvB5pOqhSEGaY05zHHKtjNsuf3h+xQkwCgYIKoZI
                zj0EAwIDSAAwRQIhALWSgw9QsKWKE5jIHpp3hxtGO98T8VgaWAVxKWEN6X0OAiBE
                jBW6Kc9lbiRWpf5sgDd8clrNsLiapyHhGrq3TApxOA==
                -----END CERTIFICATE-----

        grpcOptions:
            ssl-target-name-override: orderer.ipng.libriciel.fr
peers:
    peer0.org1.ipng.libriciel.fr:
        url: grpcs://peer0.org1.ipng.libriciel.fr:7051
        tlsCACerts:
            pem: |
                -----BEGIN CERTIFICATE-----
                MIICcjCCAhigAwIBAgIRAIkrhfEBlqscb4L/AJxwtGYwCgYIKoZIzj0EAwIwgYIx
                CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
                RnJhbmNpc2NvMR8wHQYDVQQKExZvcmcxLmlwbmcubGlicmljaWVsLmZyMSUwIwYD
                VQQDExx0bHNjYS5vcmcxLmlwbmcubGlicmljaWVsLmZyMB4XDTE5MTIwNDEwNTMw
                MFoXDTI5MTIwMTEwNTMwMFowgYIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxp
                Zm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKExZvcmcxLmlw
                bmcubGlicmljaWVsLmZyMSUwIwYDVQQDExx0bHNjYS5vcmcxLmlwbmcubGlicmlj
                aWVsLmZyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEK8G/rb161YSOGXFXJhze
                XpX2UUPy4l8RVzGcJNzhqtptz8PgLGH/GBd5gKywH6W8wHDAMo/Ql2qvOY25hEgB
                TaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
                BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAvc33hciY3eU/yvXBZbqyK
                5XSsMoUWNkkiAwNMYtxYODAKBggqhkjOPQQDAgNIADBFAiEA+uGlwhCcyDghWOIk
                00tZlCbUcFKm0r3b3oyioElBelICIB7oPNBXS6cEtsiIhJpRNx0SLTfeweS2M7y4
                dGcO7553
                -----END CERTIFICATE-----

        grpcOptions:
            ssl-target-name-override: peer0.org1.ipng.libriciel.fr
            hostnameOverride: peer0.org1.ipng.libriciel.fr
    peer1.org1.ipng.libriciel.fr:
        url: grpcs://peer1.org1.ipng.libriciel.fr:8051
        tlsCACerts:
            pem: |
                -----BEGIN CERTIFICATE-----
                MIICcjCCAhigAwIBAgIRAIkrhfEBlqscb4L/AJxwtGYwCgYIKoZIzj0EAwIwgYIx
                CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
                RnJhbmNpc2NvMR8wHQYDVQQKExZvcmcxLmlwbmcubGlicmljaWVsLmZyMSUwIwYD
                VQQDExx0bHNjYS5vcmcxLmlwbmcubGlicmljaWVsLmZyMB4XDTE5MTIwNDEwNTMw
                MFoXDTI5MTIwMTEwNTMwMFowgYIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxp
                Zm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKExZvcmcxLmlw
                bmcubGlicmljaWVsLmZyMSUwIwYDVQQDExx0bHNjYS5vcmcxLmlwbmcubGlicmlj
                aWVsLmZyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEK8G/rb161YSOGXFXJhze
                XpX2UUPy4l8RVzGcJNzhqtptz8PgLGH/GBd5gKywH6W8wHDAMo/Ql2qvOY25hEgB
                TaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
                BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCAvc33hciY3eU/yvXBZbqyK
                5XSsMoUWNkkiAwNMYtxYODAKBggqhkjOPQQDAgNIADBFAiEA+uGlwhCcyDghWOIk
                00tZlCbUcFKm0r3b3oyioElBelICIB7oPNBXS6cEtsiIhJpRNx0SLTfeweS2M7y4
                dGcO7553
                -----END CERTIFICATE-----

        grpcOptions:
            ssl-target-name-override: peer1.org1.ipng.libriciel.fr
            hostnameOverride: peer1.org1.ipng.libriciel.fr
    peer0.org2.ipng.libriciel.fr:
        url: grpcs://peer0.org2.ipng.libriciel.fr:9051
        tlsCACerts:
            pem: |
                -----BEGIN CERTIFICATE-----
                MIICcTCCAhigAwIBAgIRALH8CjsUGld4GJ/8mtGW4UwwCgYIKoZIzj0EAwIwgYIx
                CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
                RnJhbmNpc2NvMR8wHQYDVQQKExZvcmcyLmlwbmcubGlicmljaWVsLmZyMSUwIwYD
                VQQDExx0bHNjYS5vcmcyLmlwbmcubGlicmljaWVsLmZyMB4XDTE5MTIwNDEwNTMw
                MFoXDTI5MTIwMTEwNTMwMFowgYIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxp
                Zm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKExZvcmcyLmlw
                bmcubGlicmljaWVsLmZyMSUwIwYDVQQDExx0bHNjYS5vcmcyLmlwbmcubGlicmlj
                aWVsLmZyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8XoBXhyVXeHdDjMV0Vxs
                psoKa9BUMqnxTThPjN+O4Fu5yyEv6vdPS9VDtRkudPVIKbMvLyVMda/wLyvfvD3I
                SaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
                BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCS8E+ZtEywbYKdke7NiFQU
                EuvUn/r2CE2ejeEeYfKBcDAKBggqhkjOPQQDAgNHADBEAiEA5vgQ0eg6Fz3lmXZP
                HFttfBF8Ct3y8/XGviLlQrS7qPgCHwXEqsynigsjvhIDPv3nLHHu3JiM4WN+cOBf
                qQUwH0Q=
                -----END CERTIFICATE-----

        grpcOptions:
            ssl-target-name-override: peer0.org2.ipng.libriciel.fr
            hostnameOverride: peer0.org2.ipng.libriciel.fr
    peer1.org2.ipng.libriciel.fr:
        url: grpcs://peer1.org2.ipng.libriciel.fr:10051
        tlsCACerts:
            pem: |
                -----BEGIN CERTIFICATE-----
                MIICcTCCAhigAwIBAgIRALH8CjsUGld4GJ/8mtGW4UwwCgYIKoZIzj0EAwIwgYIx
                CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1TYW4g
                RnJhbmNpc2NvMR8wHQYDVQQKExZvcmcyLmlwbmcubGlicmljaWVsLmZyMSUwIwYD
                VQQDExx0bHNjYS5vcmcyLmlwbmcubGlicmljaWVsLmZyMB4XDTE5MTIwNDEwNTMw
                MFoXDTI5MTIwMTEwNTMwMFowgYIxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxp
                Zm9ybmlhMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKExZvcmcyLmlw
                bmcubGlicmljaWVsLmZyMSUwIwYDVQQDExx0bHNjYS5vcmcyLmlwbmcubGlicmlj
                aWVsLmZyMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8XoBXhyVXeHdDjMV0Vxs
                psoKa9BUMqnxTThPjN+O4Fu5yyEv6vdPS9VDtRkudPVIKbMvLyVMda/wLyvfvD3I
                SaNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEF
                BQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCCS8E+ZtEywbYKdke7NiFQU
                EuvUn/r2CE2ejeEeYfKBcDAKBggqhkjOPQQDAgNHADBEAiEA5vgQ0eg6Fz3lmXZP
                HFttfBF8Ct3y8/XGviLlQrS7qPgCHwXEqsynigsjvhIDPv3nLHHu3JiM4WN+cOBf
                qQUwH0Q=
                -----END CERTIFICATE-----

        grpcOptions:
            ssl-target-name-override: peer1.org2.ipng.libriciel.fr
            hostnameOverride: peer1.org2.ipng.libriciel.fr
certificateAuthorities:
    ca.org1.ipng.libriciel.fr:
        url: https://ca.org1.ipng.libriciel.fr:7054
        caName: ca.org1.ipng.libriciel.fr
        tlsCACerts:
            pem: |
                -----BEGIN CERTIFICATE-----
                MIICaTCCAhCgAwIBAgIRAMNcoTQZNOrtV6Zg6TIGOFcwCgYIKoZIzj0EAwIwfzEL
                MAkGA1UEBhMCVVMxEzARBgNVBAgTCkNhbGlmb3JuaWExFjAUBgNVBAcTDVNhbiBG
                cmFuY2lzY28xHzAdBgNVBAoTFm9yZzEuaXBuZy5saWJyaWNpZWwuZnIxIjAgBgNV
                BAMTGWNhLm9yZzEuaXBuZy5saWJyaWNpZWwuZnIwHhcNMTkxMjA0MTA1MzAwWhcN
                MjkxMjAxMTA1MzAwWjB/MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5p
                YTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEfMB0GA1UEChMWb3JnMS5pcG5nLmxp
                YnJpY2llbC5mcjEiMCAGA1UEAxMZY2Eub3JnMS5pcG5nLmxpYnJpY2llbC5mcjBZ
                MBMGByqGSM49AgEGCCqGSM49AwEHA0IABA27bUf+A5I16UwFvTp4Ws0mN2FU7JJ+
                jsy6LqvmH7JauiOiLENxudD9ivxeCrERJRQ9nmjYwuNx2O8v+hu8IJCjbTBrMA4G
                A1UdDwEB/wQEAwIBpjAdBgNVHSUEFjAUBggrBgEFBQcDAgYIKwYBBQUHAwEwDwYD
                VR0TAQH/BAUwAwEB/zApBgNVHQ4EIgQgVxSLNOdwfn0H4qS3ytNAbK3aSJ/pZtAS
                xR4eysEx6iowCgYIKoZIzj0EAwIDRwAwRAIgC9XpVNpsX8tNy5mTP/u868cECX1t
                kEYYTk09Q/3WsXMCIG2BXoL/UvC0ms1d/dK2D3fxooDhXNMrgKPv5l9n18Xe
                -----END CERTIFICATE-----

        httpOptions:
            verify: false
    ca.org2.ipng.libriciel.fr:
        url: https://ca.org2.ipng.libriciel.fr:8054
        caName: ca.org2.ipng.libriciel.fr
        tlsCACerts:
            pem: |
                -----BEGIN CERTIFICATE-----
                MIICaDCCAg+gAwIBAgIQPWqEqNYJcFOz9csNiPiwNzAKBggqhkjOPQQDAjB/MQsw
                CQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZy
                YW5jaXNjbzEfMB0GA1UEChMWb3JnMi5pcG5nLmxpYnJpY2llbC5mcjEiMCAGA1UE
                AxMZY2Eub3JnMi5pcG5nLmxpYnJpY2llbC5mcjAeFw0xOTEyMDQxMDUzMDBaFw0y
                OTEyMDExMDUzMDBaMH8xCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
                MRYwFAYDVQQHEw1TYW4gRnJhbmNpc2NvMR8wHQYDVQQKExZvcmcyLmlwbmcubGli
                cmljaWVsLmZyMSIwIAYDVQQDExljYS5vcmcyLmlwbmcubGlicmljaWVsLmZyMFkw
                EwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEO9/n/ZQcJlG4jd/bviuPMau7aj1lmBe/
                xwl3YMg+LurRpNvmcrTsZtquMnWRyPoDI2/j6DMrYOTECKyVBgjCg6NtMGswDgYD
                VR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAPBgNV
                HRMBAf8EBTADAQH/MCkGA1UdDgQiBCAzJVBCgShElr3eNTymBHwPAlEAiJ0JdDw1
                x6Y5yMjOlzAKBggqhkjOPQQDAgNHADBEAiB+HV0/mljaGxFJj+T4waEejPh9/72a
                s3/VsU5QPZt6FQIgSBPX7w3m5mVotwZgzrcPb0elOUMvn4peJa+H1AD0EWo=
                -----END CERTIFICATE-----

        httpOptions:
            verify: false
```

**Comment by wassimz** [comment]
The profiles file inside the settings folder are related to channel create/update task. That's why they are not full of options. We have another generator process to generate a full connection profile file, but currently not yet exposed by any cli command.

**Comment by mvanmeerbeck** [comment]
I had to use the file `connection-profile-join-channel-org1.yaml`. Here the changes i had to do to make it work:

- add a name
- add the organizations block
- fix the peers url

```

version: "1.0"
name: bnc.com
client:
  organization: org1
  credentialStore:
    path: /var/www/xdev/bnc-hlf/build/hyperledger-fabric-network/wallets/organizations/org1.bnc.com
    cryptoStore:
      path: /var/www/xdev/bnc-hlf/build/hyperledger-fabric-network/wallets/organizations/org1.bnc.com
organizations:
  org1:
    mspid: org1MSP
    peers:
      - peer0.org1.bnc.com
      - peer1.org1.bnc.com
peers:

  peer0.org1.bnc.com:
    url: grpcs://peer0.org1.bnc.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.org1.bnc.com
      request-timeout: 120001
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /var/www/xdev/bnc-hlf/build/hyperledger-fabric-network/organizations/peerOrganizations/org1.bnc.com/peers/peer0.org1.bnc.com/msp/tlscacerts/tlsca.org1.bnc.com-cert.pem

  peer1.org1.bnc.com:
    url: grpcs://peer1.org1.bnc.com:8051
    grpcOptions:
      ssl-target-name-override: peer1.org1.bnc.com
      request-timeout: 120001
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /var/www/xdev/bnc-hlf/build/hyperledger-fabric-network/organizations/peerOrganizations/org1.bnc.com/peers/peer1.org1.bnc.com/msp/tlscacerts/tlsca.org1.bnc.com-cert.pem

  peer2.org1.bnc.com:
    url: grpcs://peer2.org1.bnc.com:9051
    grpcOptions:
      ssl-target-name-override: peer2.org1.bnc.com
      request-timeout: 120001
      grpc.keepalive_time_ms: 600000
    tlsCACerts:
      path: /var/www/xdev/bnc-hlf/build/hyperledger-fabric-network/organizations/peerOrganizations/org1.bnc.com/peers/peer2.org1.bnc.com/msp/tlscacerts/tlsca.org1.bnc.com-cert.pem


orderers:
    orderer0.bnc.com:
      url: grpcs://orderer0.bnc.com:7050
      grpcOptions:
        ssl-target-name-override: orderer0.bnc.com
        grpc-max-send-message-length: 40000
      tlsCACerts:
        path: /var/www/xdev/bnc-hlf/build/hyperledger-fabric-network/organizations/ordererOrganizations/bnc.com/tlsca/tlsca.bnc.com-cert.pem
  
```
