### ISSUE TITLE
Wrong Orderer enrollment ID

### ISSUE THREAD

**Issue by mvanmeerbeck** [bxforce/bnc-hlf#19]
The orderers enrollment fail when the orderers of org1 and org2 have the same name because it doesn't use the domain name of each org but the "ordererDomain":

```
root@ipng-org1:~/bnc# bnc enroll-orderers -f config-genesis-org1-org2.yaml
[BNC] - [Orderer Cred]: start parsing...
[BNC] - Parsing genesis input file
[BNC] - Validating config-genesis-org1-org2.yaml...
[BNC] - Input genesis file validated
[BNC] - Start parsing genesis input file
[BNC] - Genesis input file parsed
[BNC] - [Orderer Cred]: parsing done!!!
[BNC] - [Orderer Cred]: configure local docker engine to be used for the generation process !!!
[BNC] - Docker network (bnc_network) already exists
[BNC] - [Orderer Cred]: docker engine configured !!!
[BNC] - [Orderer Cred]: start CA container...
[BNC] - CA running
[BNC] - Folder OwnerShip updated successfully
[BNC] - [Orderer Cred]: CA container started (true) !!!
[BNC] - [Orderer Cred]: start generating credentials...
[BNC] - Initiate CA Client services
[BNC] - CA initialized done
[BNC] - Start enrolling Orderer CA Registrar...
[BNC] - Successfully enrolled admin user "admin and imported it into the wallet
[BNC] - The admin account is enrolled (true)
[BNC] - Enrolling Orderer CA Registrar done !!!
[BNC] - Start enrolling Orderer Admin user...
[BNC] - Successfully add user "ordererOrganizationAdmin and imported it into the wallet
[BNC] - Orderer Admin is enrolled successfully
[BNC] - Enrolling Orderer Admin user done !!!
[BNC] - Start register & enroll Orderers...
+ fabric-ca-client gencsr --csr.cn orderer0.org1.ipng.theblockchainxdev.com --csr.hosts orderer0.org1.ipng.theblockchainxdev.com,localhost -M /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com -H /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com
2020/07/20 16:26:33 [INFO] Created a default configuration file at /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com/fabric-ca-client-config.yaml
2020/07/20 16:26:33 [INFO] generating key: &{A:ecdsa S:256}
2020/07/20 16:26:33 [INFO] encoded CSR
2020/07/20 16:26:33 [INFO] Stored CSR at /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com/signcerts/orderer0.org1.ipng.theblockchainxdev.com.csr
+ set +x
[BNC] - Successfully add user "orderer0.org1.ipng.theblockchainxdev.com and imported it into the wallet
[BNC] - Orderer orderer0 is enrolled successfully
[BNC] - TLS enrolled for user orderer0.org1.ipng.theblockchainxdev.com
[BNC] - Orderer TLS orderer0 is enrolled successfully
+ fabric-ca-client gencsr --csr.cn orderer0.org1.ipng.theblockchainxdev.com --csr.hosts orderer0.org1.ipng.theblockchainxdev.com,localhost -M /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com -H /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com
2020/07/20 16:26:33 [INFO] Created a default configuration file at /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com/fabric-ca-client-config.yaml
2020/07/20 16:26:33 [INFO] generating key: &{A:ecdsa S:256}
2020/07/20 16:26:33 [INFO] encoded CSR
2020/07/20 16:26:33 [INFO] Stored CSR at /home/docker-user/bnc/build/hyperledger-fabric-network/csr/ordererOrganization.org1.ipng.theblockchainxdev.com/signcerts/orderer0.org1.ipng.theblockchainxdev.com.csr
+ set +x
[BNC] - An identity for the user (orderer0.org1.ipng.theblockchainxdev.com) already exists
[BNC] - Orderer orderer0 is enrolled successfully
[BNC] -  TypeError: Cannot read property 'enrollment' of null
[BNC] - [Orderer Cred]: credentials generated --> (false) !!!
``` 

My config-genesis-org1-org2.yaml
orderer0.org1.ipng.theblockchainxdev.com
orderer0.org2.ipng.theblockchainxdev.com

```
genesis:
  template_folder: "/home/docker-user/bnc/build/hyperledger-fabric-network"
  consensus: "raft"
  ordererDomain: "org1.ipng.theblockchainxdev.com"
  ca:
    url: "127.0.0.1"
    port: 9054
  organisations:
    - organisation: "org1"
      domain_name: "org1.ipng.theblockchainxdev.com"
      orderers:
        - orderer: "orderer0"
          host_name: "orderer0.org1.ipng.theblockchainxdev.com"
          port: 7050
      anchorPeer:
        host_name: "peer0.org1.ipng.theblockchainxdev.com"
        port: 7051
    - organisation: "org2"
      domain_name: "org2.ipng.theblockchainxdev.com"
      orderers:
        - orderer: "orderer0"
          host_name: "orderer0.org2.ipng.theblockchainxdev.com"
          port: 7050
      anchorPeer:
        host_name: "peer0.org2.ipng.theblockchainxdev.com"
        port: 7051
```
